/**
 * Writes `src/lib/display/countries.ts`: the name of each country in every language of screens,
 * from the CLDR data of the Node.js running it. Run it after adding a language:
 * `pnpm tsx scripts/generate-country-names.ts && pnpm format`.
 */
import { writeFileSync } from "node:fs";
import { LANGUAGES } from "@/lib/screens/settings";

/** ISO 3166-1 countries and territories, and Kosovo (`XK`), which Stripe uses. */
const CODES =
  "AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS XK YE YT ZA ZM ZW".split(
    " ",
  );

const tables = LANGUAGES.map((language) => {
  const names = new Intl.DisplayNames([language], { type: "region", fallback: "none" });
  const entries = CODES.map((code) => {
    const name = names.of(code);
    if (!name) throw new Error(`No ${language} name for ${code}`);
    return `    ${code}: ${JSON.stringify(name)},`;
  });
  return `  ${language}: {\n${entries.join("\n")}\n  },`;
});

const source = `// Generated by scripts/generate-country-names.ts from CLDR ${process.versions.cldr}: do not edit.
import type { Language } from "@/lib/screens/settings";

/**
 * Names of ISO 3166-1 countries and territories (and Kosovo, which Stripe uses) in each language
 * of screens, as CLDR names them. Spelled out rather than read from \`Intl.DisplayNames\`, whose
 * output depends on the ICU version: the server and the browser would disagree during hydration.
 */
export const COUNTRY_NAMES: Record<Language, Readonly<Record<string, string>>> = {
${tables.join("\n")}
};
`;

writeFileSync(new URL("../src/lib/display/countries.ts", import.meta.url), source);
